//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    
    public partial class GetMyItems_Result1
    {
        public int itemId { get; set; }
        public string ItemName { get; set; }
        public string itemDescription { get; set; }
        public string exchangeItem { get; set; }
        public string imageName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
