//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendReceiveRequest
    {
        public int id { get; set; }
        public Nullable<int> sentFrom { get; set; }
        public Nullable<int> senTo { get; set; }
        public byte[] status { get; set; }
        public Nullable<System.DateTime> sentDate { get; set; }
        public Nullable<System.DateTime> receivedDate { get; set; }
        public Nullable<System.DateTime> acceptedDate { get; set; }
    
        public virtual UsersInfo UsersInfo { get; set; }
    }
}
