//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendReceiveRequest
    {
        public int id { get; set; }
        public int itemId { get; set; }
        public int sender { get; set; }
        public Nullable<int> receiver { get; set; }
        public int status { get; set; }
        public System.DateTime sendDate { get; set; }
        public System.DateTime acceptOrRejectDate { get; set; }
        public bool isSendRequest { get; set; }
    
        public virtual GrocsharyItem GrocsharyItem { get; set; }
    }
}
