//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    
    public partial class sp_GetNotification_Result1
    {
        public int id { get; set; }
        public int itemId { get; set; }
        public string ItemName { get; set; }
        public string itemDescription { get; set; }
        public string exchangeItem { get; set; }
        public string imageName { get; set; }
        public Nullable<double> distance { get; set; }
        public string first_Name { get; set; }
        public string last_Name { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public int senderId { get; set; }
        public string addressLine { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string zipcode { get; set; }
    }
}
